(function(){
  'use strict';
  const AHVAZ=[31.3183,48.6706];
  let map=null,markers=null,shared=[];
  const style=document.createElement('style');
  style.textContent=`.directoryTitleActions{display:flex;gap:7px;align-items:center}.addBizBtn,.mapSetupBtn,.dbSetupBtn{color:#fff;text-decoration:none;border-radius:11px;padding:9px 11px;font-size:10px;font-weight:900;white-space:nowrap}.addBizBtn{background:#ff6a00}.mapSetupBtn{background:#333}.dbSetupBtn{background:#17613b}.dirGrid.full{grid-template-columns:1.2fr 1fr 1fr 1fr}.directoryMapBox{margin:12px 0 4px;border:1px solid #e7e7e7;border-radius:17px;overflow:hidden;background:#fafafa}.directoryMapHead{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:10px 11px;background:#fafafa;border-bottom:1px solid #eee;font-size:10px;color:#666}.directoryMap{height:340px}.sourceTag{display:inline-block;background:#f2f2f2;color:#666;border-radius:999px;padding:3px 6px;font-size:8px;margin-right:4px}.sourceTag.shared{background:#eaf8ef;color:#17613b}.mapBtn{display:inline-block;background:#111;color:#fff;text-decoration:none;border-radius:9px;padding:6px 8px;font-size:9px;margin-top:7px}.bizTopline{display:flex;justify-content:space-between;gap:8px;align-items:center}.healthPrompt{background:#fff7f1;border:1px solid #ffe0c8;border-radius:13px;padding:10px;font-size:10px;line-height:1.8;margin:10px 0}.dbState{display:inline-block;border-radius:999px;padding:4px 7px;background:#f0f0f0;color:#666}.dbState.on{background:#eaf8ef;color:#17613b}@media(max-width:780px){.dirGrid.full{grid-template-columns:1fr}.directoryMap{height:300px}.directoryTitle{align-items:flex-start}.directoryTitleActions{flex-direction:column;align-items:stretch}.directoryMapHead{align-items:flex-start;flex-direction:column}}`;
  document.head.appendChild(style);
  function legacyToObj(x){const p=AlanBiz.legacyPair(Number(x[1]));return{id:'legacy_'+norm(x[0])+'_'+norm(x[2]),name:x[0],top:p[0],sub:p[1],area:x[2]||'',address:x[3]||'',phone:x[4]||'',lat:null,lng:null,source:'legacy'}}
  function dedupe(list){const m=new Map();list.forEach(x=>{const k=norm(x.name)+'|'+norm(x.area);if(!m.has(k)||x.source==='shared'||x.source==='user'||x.source==='manual')m.set(k,x)});return [...m.values()]}
  function allBusinesses(){return dedupe(DATA.map(legacyToObj).concat(AlanApi.readLocal()).concat(shared))}
  function safe(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  const topSel=document.getElementById('cat'),dirGrid=document.querySelector('.dirGrid');
  topSel.innerHTML='<option value="">همه حوزه‌ها</option>'+AlanBiz.topOptions().map(x=>`<option value="${x.key}">${x.icon} ${x.label}</option>`).join('');
  const subSel=document.createElement('select');subSel.id='subcat';subSel.innerHTML='<option value="">همه زیردسته‌ها</option>';dirGrid.appendChild(subSel);dirGrid.classList.add('full');
  function renderSubFilter(){const top=topSel.value;subSel.innerHTML='<option value="">همه زیردسته‌ها</option>'+(top?AlanBiz.subOptions(top).map(x=>`<option value="${x.key}">${x.label}</option>`).join(''):'')}
  topSel.addEventListener('change',()=>{renderSubFilter();enhancedRender()});subSel.addEventListener('change',enhancedRender);
  const title=document.querySelector('.directoryTitle'),oldIcon=title.querySelector('span');if(oldIcon)oldIcon.remove();
  const actions=document.createElement('div');actions.className='directoryTitleActions';actions.innerHTML='<a class="addBizBtn" href="add-business.html">＋ افزودن کسب‌وکار</a><a class="dbSetupBtn" href="backend-setup.html">☁ دیتابیس</a><a class="mapSetupBtn" href="map-setup.html">⚙ نقشه</a>';title.appendChild(actions);
  const mapBox=document.createElement('div');mapBox.className='directoryMapBox';mapBox.innerHTML='<div class="directoryMapHead"><b>نقشه کسب‌وکارها</b><span><span id="dbState" class="dbState">داده محلی</span> · <span id="mapProvider">در حال بارگذاری…</span> · <span id="mapCount">۰ نقطه</span></span></div><div id="businessMap" class="directoryMap"></div>';
  document.querySelector('.dirPanel').insertBefore(mapBox,document.getElementById('count').nextSibling);
  const healthHint=document.createElement('div');healthHint.className='healthPrompt';healthHint.innerHTML='🩺 حوزه «پزشکی و سلامت» شامل دندانپزشکی، متخصصان دندانپزشکی، پزشک عمومی و متخصص، کلینیک، داروخانه، آزمایشگاه، تصویربرداری، فیزیوتراپی و چند زیرگروه دیگر است.';mapBox.before(healthHint);
  async function initMap(){try{const state=await AlanMapProvider.create('businessMap',{center:AHVAZ,zoom:12.5});map=state.map;markers=L.layerGroup().addTo(map);document.getElementById('mapProvider').textContent=state.provider==='neshan'?'نشان':'OpenStreetMap';enhancedRender();setTimeout(()=>map.invalidateSize(),120)}catch(e){document.getElementById('mapProvider').textContent='خطا در نقشه';console.error(e)}}
  function refreshMap(list){if(!map||!markers)return;markers.clearLayers();const geo=list.filter(x=>Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lng)));geo.forEach(x=>L.marker([Number(x.lat),Number(x.lng)]).addTo(markers).bindPopup(`<b>${safe(x.name)}</b><br>${safe(AlanBiz.subLabel(x.top,x.sub))}<br>${safe(x.area)}<br>${safe(x.address)}`));document.getElementById('mapCount').textContent=`${geo.length.toLocaleString('fa-IR')} نقطه`;if(geo.length===1)map.setView([Number(geo[0].lat),Number(geo[0].lng)],16);else if(geo.length>1){const b=L.latLngBounds(geo.map(x=>[Number(x.lat),Number(x.lng)]));map.fitBounds(b.pad(.18),{maxZoom:15})}else map.setView(AHVAZ,12.5)}
  function card(x){let src='<span class="sourceTag">بانک اولیه</span>';if(x.source==='shared'||x.source==='user'||x.source==='admin'||x.source==='neshan')src='<span class="sourceTag shared">بانک مشترک</span>';else if(x.source==='manual')src='<span class="sourceTag">ثبت روی این دستگاه</span>';const mapLink=x.lat&&x.lng?AlanMapProvider.neshanPoint(x.lat,x.lng):'';return `<div class="biz"><div class="bizTopline"><span class="tag">${safe(AlanBiz.subLabel(x.top,x.sub))}</span>${src}</div><h3>${safe(x.name)}</h3><div class="mini">📍 ${safe(x.area||'محله نامشخص')}<br>${safe(x.address||'آدرس هنوز تکمیل نشده')}${x.phone?`<br>☎ <a href="tel:${safe(x.phone)}">${safe(x.phone)}</a>`:''}</div>${mapLink?`<a class="mapBtn" target="_blank" rel="noopener" href="${mapLink}">مسیریابی با نشان</a>`:''}</div>`}
  function enhancedRender(){const qq=norm(q.value),aa=norm(area.value),top=topSel.value,sub=subSel.value;let all=allBusinesses(),r=all.filter(x=>{const t=norm([x.name,x.area,x.address,AlanBiz.topLabel(x.top),AlanBiz.subLabel(x.top,x.sub)].join(' '));return(!qq||t.includes(qq))&&(!aa||t.includes(aa))&&(!top||x.top===top)&&(!sub||x.sub===sub)});count.textContent=`${r.length.toLocaleString('fa-IR')} نتیجه از ${all.length.toLocaleString('fa-IR')} کسب‌وکار`;businesses.innerHTML=r.length?r.slice(0,80).map(card).join('')+(r.length>80?'<div class="biz"><div class="mini">۸۰ نتیجه اول نمایش داده شده؛ جست‌وجو را دقیق‌تر کن.</div></div>':''):'<div class="empty">در این دسته هنوز رکوردی ثبت نشده.<br><a class="addBizBtn" style="display:inline-block;margin-top:10px" href="add-business.html">اولین کسب‌وکار را اضافه کن</a></div>';refreshMap(r)}
  async function loadShared(){const el=document.getElementById('dbState');if(!AlanApi.configured()){el.textContent='داده محلی';return}el.textContent='اتصال…';try{const r=await AlanApi.listBusinesses({city:'اهواز',limit:500});shared=(r.items||[]).map(x=>({...x,source:x.source||'shared'}));el.textContent='دیتابیس مشترک';el.classList.add('on');enhancedRender()}catch(e){el.textContent='سرور در دسترس نیست';console.warn('shared database unavailable',e)}}
  [q,area].forEach(el=>el.addEventListener('input',enhancedRender));renderSubFilter();enhancedRender();window.renderBusinesses=enhancedRender;initMap();loadShared();
})();